### ISSUE TITLE
[Packaging] Support multiple so extensions in the same packaging.

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-php#113]
For every PHP version the `so` files that are generated are specific for that version, therefore it is required to create a package that includes all the so files and the post-install.sh script to be smart enough to configure the php.ini accordingly.

### Tasks
- [x] Adapt .ci/Makefile to copy the generated `so` files to the build folder.
- [x] Adapt packaging/Makefile to consume the above generated files that were copied to the build folder.
- [x] Adapt the post-install.sh script to be smart enough to configure the php.ini file
