### ISSUE TITLE
Package Agent as .deb for Ubuntu, Debian, etc. Linux distros

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#72]
Package should:
- Install extension binary
- Install PHP part of the agent
- Update php.ini file(s) including setting `elastic_apm.bootstrap_php_part_file`

### Tasks

- [x] PoC -> https://github.com/elastic/apm-agent-php/pull/79 
- [x] Define what the installation needs to do. -> https://github.com/elastic/apm-agent-php/pull/98
- [x] Agree the folder layout. -> See https://github.com/elastic/apm-agent-php/issues/107
- [x] Follow-up regarding functional testing and non-functional testing (installing, uninstalling, upgrading ...). See https://github.com/elastic/apm-agent-php/issues/100
- [x] Support versioning for PRs that are unique and compatible with the package manager. See https://github.com/elastic/apm-agent-php/issues/108
- [x] Create smoke tests to verify the package gets installed as expected.
- [x] Confirm what data to be replaced in the package metadata.

**Comment by v1v** [comment]
Very first approach to support the package generation with fpm:
- https://github.com/elastic/apm-agent-php/pull/79

**Comment by v1v** [comment]
Regarding the folder structure, as far as I see some other PHP olugins/extensions provide the below structure:

- https://packages.debian.org/stretch/all/php-mail/filelist

```
/usr/share/doc/php-mail/changelog.Debian.gz
/usr/share/doc/php-mail/changelog.gz
/usr/share/doc/php-mail/copyright
/usr/share/doc/php-mail/package.xml.gz
/usr/share/php/.registry/mail.reg
/usr/share/php/Mail.php
/usr/share/php/Mail/RFC822.php
```

- https://packages.debian.org/stretch/all/php-horde-service-twitter/filelist

```
/usr/share/doc/php-horde-service-twitter/changelog.Debian.gz
/usr/share/doc/php-horde-service-twitter/changelog.gz
/usr/share/doc/php-horde-service-twitter/copyright
/usr/share/doc/php-horde-service-twitter/examples/twitter_browser.php
/usr/share/doc/php-horde-service-twitter/examples/twitter_cli.php
/usr/share/doc/php-horde-service-twitter/package.xml.gz
/usr/share/php/.registry/.channel.pear.horde.org/horde_service_twitter.reg
/usr/share/php/Horde/Service/Twitter.php
/usr/share/php/Horde/Service/Twitter/Account.php
/usr/share/php/Horde/Service/Twitter/Auth.php
```

So we could potentially use `/usr/share/php/elastic/apm-agent` and `/usr/share/doc/php-elastic-apm-agent/`, what do you think?

**Comment by v1v** [comment]
This has been implemented, so I'll close it now
